<!DOCTYPE html>
<html><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8"><meta name="viewport" content="width=device-width"><title>http://jenkinsapplication-env.eba-h2xz3t42.eu-central-1.elasticbeanstalk.com/</title><link rel="stylesheet" type="text/css" href="resource://content-accessible/viewsource.css"></head><body id="viewsource" class="highlight" style="-moz-tab-size: 4"><pre id="line1"><span></span><span class="doctype">&lt;!doctype html&gt;</span><span>
<span id="line2"></span></span><span>&lt;<span class="start-tag">html</span> <span class="attribute-name">lang</span>="<a class="attribute-value">en</a>"&gt;</span><span>
<span id="line3"></span></span><span>&lt;<span class="start-tag">head</span>&gt;</span><span>
<span id="line4"></span>    </span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">charset</span>="<a class="attribute-value">utf-8</a>"&gt;</span><span>
<span id="line5"></span>    </span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">http-equiv</span>="<a class="attribute-value">X-UA-Compatible</a>" <span class="attribute-name">content</span>="<a class="attribute-value">IE=edge,chrome=1</a>"&gt;</span><span>
<span id="line6"></span>    </span><span>&lt;<span class="start-tag">title</span>&gt;</span><span>PHP Application - AWS Elastic Beanstalk</span><span>&lt;/<span class="end-tag">title</span>&gt;</span><span>
<span id="line7"></span>    </span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">name</span>="<a class="attribute-value">viewport</a>" <span class="attribute-name">content</span>="<a class="attribute-value">width=device-width</a>"&gt;</span><span>
<span id="line8"></span>    </span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">stylesheet</a>" <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://fonts.googleapis.com/css?family=Lobster+Two">http://fonts.googleapis.com/css?family=Lobster+Two</a>" <span class="attribute-name">type</span>="<a class="attribute-value">text/css</a>"&gt;</span><span>
<span id="line9"></span>    </span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">icon</a>" <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:https://awsmedia.s3.amazonaws.com/favicon.ico">https://awsmedia.s3.amazonaws.com/favicon.ico</a>" <span class="attribute-name">type</span>="<a class="attribute-value">image/ico</a>" &gt;</span><span>
<span id="line10"></span>    </span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">shortcut icon</a>" <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:https://awsmedia.s3.amazonaws.com/favicon.ico">https://awsmedia.s3.amazonaws.com/favicon.ico</a>" <span class="attribute-name">type</span>="<a class="attribute-value">image/ico</a>" &gt;</span><span>
<span id="line11"></span>    </span><span class="comment">&lt;!--[if IE]&gt;&lt;script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"&gt;&lt;/script&gt;&lt;![endif]--&gt;</span><span>
<span id="line12"></span>    </span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">stylesheet</a>" <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://jenkinsapplication-env.eba-h2xz3t42.eu-central-1.elasticbeanstalk.com/styles.css">/styles.css</a>" <span class="attribute-name">type</span>="<a class="attribute-value">text/css</a>"&gt;</span><span>
<span id="line13"></span></span><span>&lt;/<span class="end-tag">head</span>&gt;</span><span>
<span id="line14"></span></span><span>&lt;<span class="start-tag">body</span>&gt;</span><span>
<span id="line15"></span>    </span><span>&lt;<span class="start-tag">section</span> <span class="attribute-name">class</span>="<a class="attribute-value">congratulations</a>"&gt;</span><span>
<span id="line16"></span>        </span><span>&lt;<span class="start-tag">h1</span>&gt;</span><span>Congratulations!</span><span>&lt;/<span class="end-tag">h1</span>&gt;</span><span>
<span id="line17"></span>        </span><span>&lt;<span class="start-tag">p</span>&gt;</span><span>Your AWS Elastic Beanstalk </span><span>&lt;<span class="start-tag">em</span>&gt;</span><span>PHP</span><span>&lt;/<span class="end-tag">em</span>&gt;</span><span> application is now running on your own dedicated environment in the AWS<span class="entity"><span>&amp;</span>nbsp;</span>Cloud</span><span>&lt;/<span class="end-tag">p</span>&gt;</span><span>
<span id="line18"></span>        </span><span>&lt;<span class="start-tag">p</span>&gt;</span><span>You are running PHP version 8.0.8</span><span>&lt;/<span class="end-tag">p</span>&gt;</span><span>
<span id="line19"></span>        </span><span>&lt;<span class="start-tag">p</span>&gt;</span><span>This environment is launched with Elastic Beanstalk PHP Platform</span><span>&lt;/<span class="end-tag">p</span>&gt;</span><span>
<span id="line20"></span>    </span><span>&lt;/<span class="end-tag">section</span>&gt;</span><span>
<span id="line21"></span>
<span id="line22"></span>    </span><span>&lt;<span class="start-tag">section</span> <span class="attribute-name">class</span>="<a class="attribute-value">instructions</a>"&gt;</span><span>
<span id="line23"></span>        </span><span>&lt;<span class="start-tag">h2</span>&gt;</span><span>What's Next?</span><span>&lt;/<span class="end-tag">h2</span>&gt;</span><span>
<span id="line24"></span>        </span><span>&lt;<span class="start-tag">ul</span>&gt;</span><span>
<span id="line25"></span>            </span><span>&lt;<span class="start-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://docs.amazonwebservices.com/elasticbeanstalk/latest/dg/">http://docs.amazonwebservices.com/elasticbeanstalk/latest/dg/</a>"&gt;</span><span>AWS Elastic Beanstalk overview</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line26"></span>            </span><span>&lt;<span class="start-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://docs.amazonwebservices.com/elasticbeanstalk/latest/dg/create_deploy_PHP_eb.html">http://docs.amazonwebservices.com/elasticbeanstalk/latest/dg/create_deploy_PHP_eb.html</a>"&gt;</span><span>Deploying AWS Elastic Beanstalk Applications in PHP Using Eb and Git</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line27"></span>            </span><span>&lt;<span class="start-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://docs.amazonwebservices.com/elasticbeanstalk/latest/dg/create_deploy_PHP.rds.html">http://docs.amazonwebservices.com/elasticbeanstalk/latest/dg/create_deploy_PHP.rds.html</a>"&gt;</span><span>Using Amazon RDS with PHP</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span>
<span id="line28"></span>            </span><span>&lt;<span class="start-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://docs.amazonwebservices.com/elasticbeanstalk/latest/dg/customize-containers-ec2.html">http://docs.amazonwebservices.com/elasticbeanstalk/latest/dg/customize-containers-ec2.html</a>"&gt;</span><span>Customizing the Software on EC2 Instances</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line29"></span>            </span><span>&lt;<span class="start-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://docs.amazonwebservices.com/elasticbeanstalk/latest/dg/customize-containers-resources.html">http://docs.amazonwebservices.com/elasticbeanstalk/latest/dg/customize-containers-resources.html</a>"&gt;</span><span>Customizing Environment Resources</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line30"></span>        </span><span>&lt;/<span class="end-tag">ul</span>&gt;</span><span>
<span id="line31"></span>
<span id="line32"></span>        </span><span>&lt;<span class="start-tag">h2</span>&gt;</span><span>AWS SDK for PHP</span><span>&lt;/<span class="end-tag">h2</span>&gt;</span><span>
<span id="line33"></span>        </span><span>&lt;<span class="start-tag">ul</span>&gt;</span><span>
<span id="line34"></span>            </span><span>&lt;<span class="start-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://aws.amazon.com/sdkforphp">http://aws.amazon.com/sdkforphp</a>"&gt;</span><span>AWS SDK for PHP home</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line35"></span>            </span><span>&lt;<span class="start-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:http://aws.amazon.com/php">http://aws.amazon.com/php</a>"&gt;</span><span>PHP developer center</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line36"></span>            </span><span>&lt;<span class="start-tag">li</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:https://github.com/aws/aws-sdk-php">https://github.com/aws/aws-sdk-php</a>"&gt;</span><span>AWS SDK for PHP on GitHub</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">li</span>&gt;</span><span>
<span id="line37"></span>        </span><span>&lt;/<span class="end-tag">ul</span>&gt;</span><span>
<span id="line38"></span>    </span><span>&lt;/<span class="end-tag">section</span>&gt;</span><span>
<span id="line39"></span>
<span id="line40"></span>    </span><span class="comment">&lt;!--[if lt IE 9]&gt;&lt;script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"&gt;&lt;/script&gt;&lt;![endif]--&gt;</span><span>
<span id="line41"></span></span><span>&lt;/<span class="end-tag">body</span>&gt;</span><span>
<span id="line42"></span></span><span>&lt;/<span class="end-tag">html</span>&gt;</span><span>
<span id="line43"></span></span></pre></body></html>